/// Flutter icons Insta_clone
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Insta_clone
///      fonts:
///       - asset: fonts/Insta_clone.ttf
///
///
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class Insta_clone {
  Insta_clone._();

  static const _kFontFam = 'Insta_clone';
  static const String? _kFontPkg = null;

  static const IconData image2vector =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xf35f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
